#ifndef ANTLAND_H
#define ANTLAND_H

#include "common.h"
#include "PR/gu.h"

extern unsigned char Global_brickWall_i4_PNG[];
extern unsigned char Global_brownBrickWall_ci4_PAL[];
extern unsigned char Global_brownBrickWall_ci4_PNG[];
extern unsigned char Global_antMural2_i4_PNG[];
extern unsigned char Global_antMural1_i4_PNG[];
extern unsigned char Global_dcRockFloor_i4_PNG[];
extern unsigned char Global_yellowBrickWall_ci4_PAL[];
extern unsigned char Global_yellowBrickWall_ci4_PNG[];
extern unsigned char Global_smallBrickWall_i4_PNG[];
extern unsigned char Global_bigBrickWall_i4_PNG[];
extern unsigned char Global_brickWall2_ci4_PAL[];
extern unsigned char Global_brickWall2_ci4_PNG[];
extern unsigned char Global_antMural3_i4_PNG[];
extern unsigned char Global_unk12_i4_PNG[];
extern unsigned char Global_bigBrickWall2_i4_PNG[];
extern unsigned char Global_antMural4_i4_PNG[];
extern unsigned char Global_gravel_i4_PNG[];
extern unsigned char Global_goldStrip_ci4_PAL[];
extern unsigned char Global_goldStrip_ci4_PNG[];
extern unsigned char Global_waterKinda_ci4_PAL[];
extern unsigned char Global_waterKinda_ci4_PNG[];
extern unsigned char Global_dcRockFloorColor_ci4_PAL[];
extern unsigned char Global_dcRockFloorColor_ci4_PNG[];
extern unsigned char Global_gateGray_ia4_PNG[];
extern unsigned char Global_wall_i4_PNG[];

#include "global_models.h"

extern Gfx AntLand_exit2_Gfx[];
extern ModelCollision AntLand_exit2_collision;
extern Gfx AntLand_exit3_Gfx[];
extern ModelCollision AntLand_exit3_collision;
extern Gfx AntLand_exit4_Gfx[];
extern ModelCollision AntLand_exit4_collision;
extern Gfx AntLand_room0_Gfx[];
extern ModelCollision AntLand_room0_collision;
extern Gfx AntLand_room1_Gfx[];
extern ModelCollision AntLand_room1_collision;
extern Gfx AntLand_room2_Gfx[];
extern ModelCollision AntLand_room2_collision;
extern Gfx AntLand_room14_Gfx[];
extern ModelCollision AntLand_room14_collision;
extern Gfx AntLand_room4_Gfx[];
extern ModelCollision AntLand_room4_collision;
extern Gfx AntLand_room5_Gfx[];
extern ModelCollision AntLand_room5_collision;
extern Gfx AntLand_room6_Gfx[];
extern ModelCollision AntLand_room6_collision;
extern Gfx AntLand_room7_Gfx[];
extern ModelCollision AntLand_room7_collision;
extern Gfx AntLand_room8_Gfx[];
extern ModelCollision AntLand_room8_collision;
extern Gfx AntLand_room9_Gfx[];
extern ModelCollision AntLand_room9_collision;
extern Gfx AntLand_room10_Gfx[];
extern ModelCollision AntLand_room10_collision;
extern Gfx AntLand_room11_Gfx[];
extern ModelCollision AntLand_room11_collision;
extern Gfx AntLand_room12_Gfx[];
extern ModelCollision AntLand_room12_collision;
extern Gfx AntLand_room13_Gfx[];
extern ModelCollision AntLand_room13_collision;
extern Gfx AntLand_room3_Gfx[];
extern ModelCollision AntLand_room3_collision;
extern Gfx AntLand_room17_Gfx[];
extern ModelCollision AntLand_room17_collision;
extern Gfx AntLand_room15_Gfx[];
extern ModelCollision AntLand_room15_collision;
extern Gfx AntLand_room18_Gfx[];
extern ModelCollision AntLand_room18_collision;
extern Gfx AntLand_room16_Gfx[];
extern ModelCollision AntLand_room16_collision;
extern Gfx AntLand_room20_Gfx[];
extern ModelCollision AntLand_room20_collision;
extern Gfx AntLand_room21_Gfx[];
extern ModelCollision AntLand_room21_collision;
extern Gfx AntLand_room4Platform_Gfx[];
extern ModelCollision AntLand_room4Platform_collision;
extern Gfx AntLand_room4Floor_Gfx[];
extern ModelCollision AntLand_room4Floor_collision;
extern Gfx AntLand_room6Floor_Gfx[];
extern ModelCollision AntLand_room6Floor_collision;
extern Gfx AntLand_room8Floor_Gfx[];
extern ModelCollision AntLand_room8Floor_collision;
extern Gfx AntLand_room17Floor_Gfx[];
extern ModelCollision AntLand_room17Floor_collision;
extern Gfx AntLand_room10Floor_Gfx[];
extern ModelCollision AntLand_room10Floor_collision;
extern Gfx AntLand_room10Platform1_Gfx[];
extern ModelCollision AntLand_room10Platform1_collision;
extern Gfx AntLand_room10Platform2_Gfx[];
extern ModelCollision AntLand_room10Platform2_collision;
extern Gfx AntLand_room10Platform3_Gfx[];
extern ModelCollision AntLand_room10Platform3_collision;
extern Gfx AntLand_room5Platform_Gfx[];
extern ModelCollision AntLand_room5Platform_collision;
extern Gfx AntLand_room13Platform_Gfx[];
extern ModelCollision AntLand_room13Platform_collision;
extern Gfx AntLand_room21Platform1_Gfx[];
extern ModelCollision AntLand_room21Platform1_collision;
extern Gfx AntLand_room21Platform2_Gfx[];
extern ModelCollision AntLand_room21Platform2_collision;
extern Gfx AntLand_room12Floor1_Gfx[];
extern ModelCollision AntLand_room12Floor1_collision;
extern Gfx AntLand_room12Floor2_Gfx[];
extern ModelCollision AntLand_room12Floor2_collision;
extern Gfx AntLand_room11Floor1_Gfx[];
extern ModelCollision AntLand_room11Floor1_collision;
extern Gfx AntLand_room11Floor2_Gfx[];
extern ModelCollision AntLand_room11Floor2_collision;
extern Gfx AntLand_room4Grate_Gfx[];
extern ModelCollision AntLand_room4Grate_collision;
extern Gfx AntLand_room7Floor_Gfx[];
extern ModelCollision AntLand_room7Floor_collision;
extern Gfx AntLand_room7Ceiling_Gfx[];
extern ModelCollision AntLand_room7Ceiling_collision;
extern Gfx AntLand_room15Floor_Gfx[];
extern ModelCollision AntLand_room15Floor_collision;
extern Gfx AntLand_room15Ceiling_Gfx[];
extern ModelCollision AntLand_room15Ceiling_collision;
extern Gfx AntLand_room8Floor1_Gfx[];
extern ModelCollision AntLand_room8Floor1_collision;
extern Gfx AntLand_room8Floor2_Gfx[];
extern ModelCollision AntLand_room8Floor2_collision;
extern Gfx AntLand_room0doorPillar1_Gfx[];
extern ModelCollision AntLand_room0doorPillar1_collision;
extern Gfx AntLand_room0doorPillar2_Gfx[];
extern ModelCollision AntLand_room0doorPillar2_collision;
extern Gfx AntLand_room0doorTop_Gfx[];
extern ModelCollision AntLand_room0doorTop_collision;
extern Gfx AntLand_room0doorTorchStand1_Gfx[];
extern ModelCollision AntLand_room0doorTorchStand1_collision;
extern Gfx AntLand_room0doorTorchStand2_Gfx[];
extern ModelCollision AntLand_room0doorTorchStand2_collision;
extern Gfx AntLand_room16Floor1_Gfx[];
extern ModelCollision AntLand_room16Floor1_collision;
extern Gfx AntLand_room16Floor2_Gfx[];
extern ModelCollision AntLand_room16Floor2_collision;
extern Gfx AntLand_room16Grate_Gfx[];
extern ModelCollision AntLand_room16Grate_collision;
extern Gfx AntLand_tiltPlatform_Gfx[];
extern ModelCollision AntLand_tiltPlatform_collision;
extern Gfx AntLand_platform_Gfx[];
extern ModelCollision AntLand_platform_collision;
extern Gfx AntLand_movingPlatform_Gfx[];
extern ModelCollision AntLand_movingPlatform_collision;
extern Gfx AntLand_quad_Gfx[];
extern ModelCollision AntLand_quad_collision;
extern Gfx AntLand_fixedCamPillar_Gfx[];
extern ModelCollision AntLand_fixedCamPillar_collision;
extern Gfx Global_pole_Gfx[];
extern ModelCollision Global_pole_collision;

#endif
