#ifndef DESERTCASTLE_H
#define DESERTCASTLE_H

#include "common.h"
extern Vtx D_800FE2B0_DesertCastle[];

extern unsigned char Global_sandAgain_ci4_PNG[];
extern unsigned char Global_sandAgain_ci4_PAL[];
extern unsigned char Global_DCSmallTiles_ci4_PNG[];
extern unsigned char Global_DCSmallTiles_ci4_PAL[];
extern unsigned char Global_DCThing1_ci4_PNG[];
extern unsigned char Global_DCThing1_ci4_PAL[];
extern unsigned char Global_DCWall3_ci4_PNG[];
extern unsigned char Global_DCWall3_ci4_PAL[];
extern unsigned char Global_DCFloor2_ci4_PNG[];
extern unsigned char Global_DCFloor2_ci4_PAL[];
extern unsigned char Global_DCBricks_ci4_PNG[];
extern unsigned char Global_DCBricks_ci4_PAL[];
extern unsigned char Global_dcTHING2_ci4_PNG[];
extern unsigned char Global_dcTHING2_ci4_PAL[];
extern unsigned char Global_DCSandFloor_ci4_PNG[];
extern unsigned char Global_DCSandFloor_ci4_PAL[];
extern unsigned char Global_pebbles_ci4_PNG[];
extern unsigned char Global_pebbles_ci4_PAL[];
extern unsigned char Global_ropeChroma_ci8_PNG[];
extern unsigned char Global_ropeChroma_ci8_PAL[];
extern unsigned char Global_DCWall2_ci4_PNG[];
extern unsigned char Global_DCWall2_ci4_PAL[];
extern unsigned char Global_DCThing2_ci4_PNG[];
extern unsigned char Global_DCThing2_ci4_PAL[];
extern unsigned char Global_DCThing3_ci4_PNG[];
extern unsigned char Global_DCThing3_ci4_PAL[];
extern unsigned char Global_smallBrickWall_i4_PNG[];
extern unsigned char Global_DCFloor_ci4_PNG[];
extern unsigned char Global_DCFloor_ci4_PAL[];

#include "global_models.h"
extern Gfx DesertCastle_model1_Gfx[];
extern ModelCollision DesertCastle_unkCol1_collision;
extern Gfx DesertCastle_model2_Gfx[];
extern ModelCollision DesertCastle_unkCol2_collision;
extern Gfx DesertCastle_model3_Gfx[];
extern ModelCollision DesertCastle_unkCol3_collision;
extern Gfx DesertCastle_model4_Gfx[];
extern ModelCollision DesertCastle_unkCol4_collision;
extern Gfx DesertCastle_model5_Gfx[];
extern ModelCollision DesertCastle_unkCol5_collision;
extern Gfx DesertCastle_model6_Gfx[];
extern ModelCollision DesertCastle_unkCol6_collision;
extern Gfx DesertCastle_model7_Gfx[];
extern ModelCollision DesertCastle_unkCol7_collision;
extern Gfx DesertCastle_model8_Gfx[];
extern ModelCollision DesertCastle_unkCol8_collision;
extern Gfx DesertCastle_model9_Gfx[];
extern ModelCollision DesertCastle_unkCol9_collision;
extern Gfx DesertCastle_model10_Gfx[];
extern ModelCollision DesertCastle_unkCol10_collision;
extern Gfx DesertCastle_model11_Gfx[];
extern ModelCollision DesertCastle_unkCol11_collision;
extern Gfx DesertCastle_model12_Gfx[];
extern ModelCollision DesertCastle_unkCol12_collision;
extern Gfx DesertCastle_model13_Gfx[];
extern ModelCollision DesertCastle_unkCol13_collision;
extern Gfx DesertCastle_model14_Gfx[];
extern ModelCollision DesertCastle_unkCol14_collision;
extern Gfx DesertCastle_model15_Gfx[];
extern ModelCollision DesertCastle_unkCol15_collision;
extern Gfx DesertCastle_model16_Gfx[];
extern ModelCollision DesertCastle_unkCol16_collision;
extern Gfx DesertCastle_model17_Gfx[];
extern ModelCollision DesertCastle_unkCol17_collision;
extern Gfx DesertCastle_model18_Gfx[];
extern ModelCollision DesertCastle_unkCol18_collision;
extern Gfx DesertCastle_model19_Gfx[];
extern ModelCollision DesertCastle_unkCol19_collision;
extern Gfx DesertCastle_model20_Gfx[];
extern ModelCollision DesertCastle_unkCol20_collision;
extern Gfx DesertCastle_model21_Gfx[];
extern ModelCollision DesertCastle_unkCol21_collision;
extern Gfx DesertCastle_model22_Gfx[];
extern ModelCollision DesertCastle_unkCol22_collision;
extern Gfx DesertCastle_model23_Gfx[];
extern ModelCollision DesertCastle_unkCol23_collision;
extern Gfx DesertCastle_model24_Gfx[];
extern ModelCollision DesertCastle_unkCol24_collision;
extern Gfx DesertCastle_model25_Gfx[];
extern ModelCollision DesertCastle_unkCol25_collision;
extern Gfx DesertCastle_model26_Gfx[];
extern ModelCollision DesertCastle_unkCol26_collision;
extern Gfx DesertCastle_model27_Gfx[];
extern ModelCollision DesertCastle_unkCol27_collision;
extern Gfx DesertCastle_model28_Gfx[];
extern ModelCollision DesertCastle_unkCol28_collision;
extern Gfx DesertCastle_model29_Gfx[];
extern ModelCollision DesertCastle_unkCol29_collision;
extern Gfx DesertCastle_model30_Gfx[];
extern ModelCollision DesertCastle_unkCol30_collision;
extern Gfx DesertCastle_model31_Gfx[];
extern ModelCollision DesertCastle_unkCol31_collision;
extern Gfx DesertCastle_model32_Gfx[];
extern ModelCollision DesertCastle_unkCol32_collision;
extern Gfx DesertCastle_model33_Gfx[];
extern ModelCollision DesertCastle_unkCol33_collision;
extern Gfx DesertCastle_model34_Gfx[];
extern ModelCollision DesertCastle_unkCol34_collision;
extern Gfx DesertCastle_model35_Gfx[];
extern ModelCollision DesertCastle_unkCol35_collision;
extern Gfx DesertCastle_model36_Gfx[];
extern ModelCollision DesertCastle_unkCol36_collision;
extern Gfx DesertCastle_model37_Gfx[];
extern ModelCollision DesertCastle_unkCol37_collision;
extern Gfx DesertCastle_model38_Gfx[];
extern ModelCollision DesertCastle_unkCol38_collision;
extern Gfx DesertCastle_model39_Gfx[];
extern ModelCollision DesertCastle_unkCol39_collision;
extern Gfx DesertCastle_model40_Gfx[];
extern ModelCollision DesertCastle_unkCol40_collision;
extern Gfx DesertCastle_model41_Gfx[];
extern ModelCollision DesertCastle_unkCol41_collision;
extern Gfx DesertCastle_model42_Gfx[];
extern ModelCollision DesertCastle_unkCol42_collision;
extern Gfx DesertCastle_model43_Gfx[];
extern ModelCollision DesertCastle_unkCol43_collision;
extern Gfx DesertCastle_model44_Gfx[];
extern ModelCollision DesertCastle_unkCol44_collision;
extern Gfx DesertCastle_model45_Gfx[];
extern ModelCollision DesertCastle_unkCol45_collision;
extern Gfx DesertCastle_model46_Gfx[];
extern ModelCollision DesertCastle_unkCol46_collision;
extern Gfx DesertCastle_model47_Gfx[];
extern ModelCollision DesertCastle_unkCol47_collision;
extern Gfx DesertCastle_model48_Gfx[];
extern ModelCollision DesertCastle_unkCol48_collision;
extern Gfx DesertCastle_model49_Gfx[];
extern ModelCollision DesertCastle_unkCol49_collision;
extern Gfx DesertCastle_model50_Gfx[];
extern ModelCollision DesertCastle_unkCol50_collision;
extern Gfx DesertCastle_model51_Gfx[];
extern ModelCollision DesertCastle_unkCol51_collision;
extern Gfx DesertCastle_model52_Gfx[];
extern ModelCollision DesertCastle_unkCol52_collision;
extern Gfx DesertCastle_model53_Gfx[];
extern ModelCollision DesertCastle_unkCol53_collision;
extern Gfx DesertCastle_model54_Gfx[];
extern ModelCollision DesertCastle_unkCol54_collision;
extern Gfx DesertCastle_model55_Gfx[];
extern ModelCollision DesertCastle_unkCol55_collision;
extern Gfx DesertCastle_model56_Gfx[];
extern ModelCollision DesertCastle_unkCol56_collision;
extern Gfx DesertCastle_model57_Gfx[];
extern ModelCollision DesertCastle_unkCol57_collision;
extern Gfx DesertCastle_model58_Gfx[];
extern ModelCollision DesertCastle_unkCol58_collision;
extern Gfx DesertCastle_model59_Gfx[];
extern ModelCollision DesertCastle_unkCol59_collision;
extern Gfx DesertCastle_model60_Gfx[];
extern ModelCollision DesertCastle_unkCol60_collision;
extern Gfx DesertCastle_model61_Gfx[];
extern ModelCollision DesertCastle_unkCol61_collision;
extern Gfx DesertCastle_model62_Gfx[];
extern ModelCollision DesertCastle_unkCol62_collision;
extern Gfx DesertCastle_model63_Gfx[];
extern ModelCollision DesertCastle_unkCol63_collision;
extern Gfx DesertCastle_model64_Gfx[];
extern ModelCollision DesertCastle_unkCol64_collision;
extern Gfx DesertCastle_model65_Gfx[];
extern ModelCollision DesertCastle_unkCol65_collision;
extern Gfx DesertCastle_model66_Gfx[];
extern ModelCollision DesertCastle_unkCol66_collision;
extern Gfx DesertCastle_model67_Gfx[];
extern ModelCollision DesertCastle_unkCol67_collision;
extern Gfx DesertCastle_model68_Gfx[];
extern ModelCollision DesertCastle_unkCol68_collision;
extern Gfx DesertCastle_model69_Gfx[];
extern ModelCollision DesertCastle_unkCol69_collision;
extern Gfx DesertCastle_model70_Gfx[];
extern ModelCollision DesertCastle_unkCol70_collision;
extern Gfx DesertCastle_model71_Gfx[];
extern ModelCollision DesertCastle_unkCol71_collision;
extern Gfx DesertCastle_model72_Gfx[];
extern ModelCollision DesertCastle_unkCol72_collision;
extern Gfx DesertCastle_model73_Gfx[];
extern ModelCollision DesertCastle_unkCol73_collision;
extern Gfx DesertCastle_model74_Gfx[];
extern ModelCollision DesertCastle_unkCol74_collision;
extern Gfx DesertCastle_model75_Gfx[];
extern ModelCollision DesertCastle_unkCol75_collision;
extern Gfx DesertCastle_model76_Gfx[];
extern ModelCollision DesertCastle_unkCol76_collision;
extern Gfx DesertCastle_model77_Gfx[];
extern ModelCollision DesertCastle_unkCol77_collision;
extern Gfx DesertCastle_model78_Gfx[];
extern ModelCollision DesertCastle_unkCol78_collision;
extern Gfx DesertCastle_model79_Gfx[];
extern ModelCollision DesertCastle_unkCol79_collision;
extern Gfx DesertCastle_model80_Gfx[];
extern ModelCollision DesertCastle_unkCol80_collision;
extern Gfx DesertCastle_model81_Gfx[];
extern ModelCollision DesertCastle_unkCol81_collision;
extern Gfx DesertCastle_model82_Gfx[];
extern ModelCollision DesertCastle_unkCol82_collision;
extern Gfx DesertCastle_model83_Gfx[];
extern ModelCollision DesertCastle_unkCol83_collision;
extern Gfx DesertCastle_model84_Gfx[];
extern ModelCollision DesertCastle_unkCol84_collision;
extern Gfx DesertCastle_model85_Gfx[];
extern ModelCollision DesertCastle_unkCol85_collision;
extern Gfx DesertCastle_model86_Gfx[];
extern ModelCollision DesertCastle_unkCol86_collision;
extern Gfx DesertCastle_model87_Gfx[];
extern ModelCollision DesertCastle_unkCol87_collision;
extern Gfx DesertCastle_model88_Gfx[];
extern ModelCollision DesertCastle_unkCol88_collision;
extern Gfx DesertCastle_model89_Gfx[];
extern ModelCollision DesertCastle_unkCol89_collision;
extern Gfx DesertCastle_model90_Gfx[];
extern ModelCollision DesertCastle_unkCol90_collision;
extern Gfx Global_pole_Gfx[];
extern ModelCollision Global_pole_collision;


#endif
