#ifndef TRAINING_H
#define TRAINING_H

#include "common.h"



extern unsigned char Global_wood_ci4_PNG[];
extern unsigned char Global_wood_ci4_PAL[];
extern unsigned char Global_GCBigCabinet_ci4_PNG[];
extern unsigned char Global_GCBigCabinet_ci4_PAL[];
extern unsigned char Global_GCWall_ci4_PNG[];
extern unsigned char Global_GCWall_ci4_PAL[];
extern unsigned char Global_water_ci4_PNG[];
extern unsigned char Global_water_ci4_PAL[];
extern unsigned char Global_windows_ia4_PNG[];
extern unsigned char Global_GCWall2_ci4_PNG[];
extern unsigned char Global_GCWall2_ci4_PAL[];
extern unsigned char Global_GCTiles_ci4_PNG[];
extern unsigned char Global_GCTiles_ci4_PAL[];
extern unsigned char Global_cracker_ci4_PNG[];
extern unsigned char Global_cracker_ci4_PAL[];
extern unsigned char Global_KLFloor2_ci4_PNG[];
extern unsigned char Global_KLFloor2_ci4_PAL[];
extern unsigned char Global_sandwSide_ci4_PNG[];
extern unsigned char Global_sandwSide_ci4_PAL[];
extern unsigned char Global_KLFloor3_ci4_PNG[];
extern unsigned char Global_KLFloor3_ci4_PAL[];
extern unsigned char Global_KLThing1_ci4_PNG[];
extern unsigned char Global_KLThing1_ci4_PAL[];
extern unsigned char Global_jlText3_ci4_PNG[];
extern unsigned char Global_jlText3_ci4_PAL[];
extern unsigned char Global_JLMountain_ci4_PNG[];
extern unsigned char Global_JLMountain_ci4_PAL[];
extern unsigned char Global_pebbles_ci4_PNG[];
extern unsigned char Global_pebbles_ci4_PAL[];
extern unsigned char Global_jlText5_ci4_PNG[];
extern unsigned char Global_jlText5_ci4_PAL[];
extern unsigned char Global_jlText2_ci4_PNG[];
extern unsigned char Global_jlText2_ci4_PAL[];
extern unsigned char Global_JLCaveFadeTop_ci8_PNG[];
extern unsigned char Global_JLCaveFadeTop_ci8_PAL[];
extern unsigned char Global_BLRedYellowPlate_ci4_PNG[];
extern unsigned char Global_BLRedYellowPlate_ci4_PAL[];
extern unsigned char Global_metalPlate_i4_PNG[];
extern unsigned char Global_squares_i4_PNG[];
extern unsigned char Global_fraMEd_ia4_PNG[];
extern unsigned char Global_lavaSolid_ci4_PAL[];
extern unsigned char Global_lavaSolid_ci4_PNG[];
extern unsigned char Global_ballGround_i4_PNG[];
extern unsigned char Global_DCFloor2_ci4_PNG[];
extern unsigned char Global_DCFloor2_ci4_PAL[];
extern unsigned char Global_DCBricks_ci4_PNG[];
extern unsigned char Global_DCBricks_ci4_PAL[];
extern unsigned char Global_sandAgain_ci4_PNG[];
extern unsigned char Global_sandAgain_ci4_PAL[];
extern unsigned char Global_brickWall2_ci4_PNG[];
extern unsigned char Global_brickWall2_ci4_PAL[];
extern unsigned char Global_waterKinda_ci4_PNG[];
extern unsigned char Global_waterKinda_ci4_PAL[];
extern unsigned char Global_yellowBrickWall_ci4_PNG[];
extern unsigned char Global_yellowBrickWall_ci4_PAL[];
extern unsigned char Global_bigBrickWall_i4_PNG[];
extern unsigned char Global_bigBrickWall2_i4_PNG[];
extern unsigned char Global_strip2_i4_PNG[];
extern unsigned char Global_justBlack_ci4_PNG[];
extern unsigned char Global_justBlack_ci4_PAL[];
extern unsigned char Global_chocoKidsLabel_ci4_PNG[];
extern unsigned char Global_chocoKidsLabel_ci4_PAL[];
extern unsigned char Global_chocoKIDS_ci8_PNG[];
extern unsigned char Global_chocoKIDS_ci8_PAL[];
extern unsigned char Global_JLCave_ci8_PNG[];
extern unsigned char Global_JLCave_ci8_PAL[];
extern unsigned char Global_jlText4_ci4_PNG[];
extern unsigned char Global_jlText4_ci4_PAL[];
extern unsigned char Global_factoryPlates_i4_PNG[];
extern unsigned char Global_steelPlate_i4_PNG[];
extern unsigned char Global_metalPlates_i4_PNG[];
extern unsigned char Global_DCSmallTiles_ci4_PNG[];
extern unsigned char Global_DCSmallTiles_ci4_PAL[];
extern unsigned char Global_DCSandFloor_ci4_PNG[];
extern unsigned char Global_DCSandFloor_ci4_PAL[];
extern unsigned char Global_DCFloor_ci4_PNG[];
extern unsigned char Global_DCFloor_ci4_PAL[];
extern unsigned char Global_DCWall3_ci4_PNG[];
extern unsigned char Global_DCWall3_ci4_PAL[];
extern unsigned char Global_DCWall2_ci4_PNG[];
extern unsigned char Global_DCWall2_ci4_PAL[];
extern unsigned char Global_DCWall1_ci4_PNG[];
extern unsigned char Global_DCWall1_ci4_PAL[];
extern unsigned char Global_DCThing3_ci4_PNG[];
extern unsigned char Global_DCThing3_ci4_PAL[];
extern unsigned char Global_goldStrip_ci4_PNG[];
extern unsigned char Global_goldStrip_ci4_PAL[];
extern unsigned char Global_antMural4_i4_PNG[];
extern unsigned char Global_DCThing2_ci4_PNG[];
extern unsigned char Global_DCThing2_ci4_PAL[];
extern unsigned char Global_DCThing1_ci4_PNG[];
extern unsigned char Global_DCThing1_ci4_PAL[];

#include "global_models.h"
extern Gfx Training_model1_Gfx[];
extern ModelCollision Training_unkCol1_collision;
extern Gfx Training_model2_Gfx[];
extern ModelCollision Training_unkCol2_collision;
extern Gfx Training_model3_Gfx[];
extern ModelCollision Training_unkCol3_collision;
extern Gfx Training_model4_Gfx[];
extern ModelCollision Training_unkCol4_collision;
extern Gfx Training_model5_Gfx[];
extern ModelCollision Training_unkCol5_collision;
extern Gfx Training_model6_Gfx[];
extern ModelCollision Training_unkCol6_collision;
extern Gfx Training_model7_Gfx[];
extern ModelCollision Training_unkCol7_collision;
extern Gfx Training_model8_Gfx[];
extern ModelCollision Training_unkCol8_collision;
extern Gfx Training_model9_Gfx[];
extern ModelCollision Training_unkCol9_collision;
extern Gfx Training_model10_Gfx[];
extern ModelCollision Training_unkCol10_collision;
extern Gfx Training_model11_Gfx[];
extern ModelCollision Training_unkCol11_collision;
extern Gfx Training_model12_Gfx[];
extern ModelCollision Training_unkCol12_collision;
extern Gfx Training_model13_Gfx[];
extern ModelCollision Training_unkCol13_collision;
extern Gfx Training_model14_Gfx[];
extern ModelCollision Training_unkCol14_collision;
extern Gfx Training_model15_Gfx[];
extern ModelCollision Training_unkCol15_collision;
extern Gfx Training_model16_Gfx[];
extern ModelCollision Training_unkCol16_collision;
extern Gfx Training_model17_Gfx[];
extern ModelCollision Training_unkCol17_collision;
extern Gfx Training_model18_Gfx[];
extern ModelCollision Training_unkCol18_collision;
extern Gfx Training_model19_Gfx[];
extern ModelCollision Training_unkCol19_collision;
extern Gfx Training_model20_Gfx[];
extern ModelCollision Training_unkCol20_collision;
extern Gfx Training_model21_Gfx[];
extern ModelCollision Training_unkCol21_collision;
extern Gfx Training_model22_Gfx[];
extern ModelCollision Training_unkCol22_collision;
extern Gfx Global_pole_Gfx[];
extern ModelCollision Global_pole_collision;


#endif
